### ISSUE TITLE
Option field should change to input field when loklak option is ticked

### ISSUE THREAD

**Issue by sopankhosla** [loklak/wp-twitter-widget-pro#6]
![selection_033](https://cloud.githubusercontent.com/assets/6399612/16053395/38055c48-3286-11e6-80cd-42414f957bf9.png)
![selection_034](https://cloud.githubusercontent.com/assets/6399612/16053396/383c28f4-3286-11e6-95de-88676e58d691.png)

This needs to be done through JS. 
Will do it ASAP!

**Comment by mariobehling** [comment]
The question is, what if a user does not have a twitter username? Should still be possible to use it.

**Comment by sopankhosla** [comment]
I agree. but it still would be a twitter username (of the person whose tweets the user wants to see) IMO
The label "Twitter username" associated with it might need to be modified to make it more clear.

**Comment by sopankhosla** [comment]
0285d7 fixes it!
