### ISSUE TITLE
Test working of the plugin with Loklak API

### ISSUE THREAD

**Issue by sopankhosla** [loklak/wp-twitter-widget-pro#7]

**Comment by sopankhosla** [comment]
Working version of the plugin is on https://somethingtothink.com/

**Comment by mariobehling** [comment]
Still getting safescript errors on you site. When will there be a page without errors that we can send to normal users to get feedback? There is tons of documentation online about Wordpress, Cloudflare and whatever you could think of. When will this error be resolved?

**Comment by sopankhosla** [comment]
I have been trying to solve this error for past week or so. With no success. I tried all hacks given in related forums. 
I will try to deploy it on heroku today.

**Comment by sopankhosla** [comment]
https://still-badlands-77870.herokuapp.com/ is the working heroku deployment.

**Comment by sopankhosla** [comment]
8114c8e3e and 354cfa9 fix the issues! Closing for now!
